import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import Background from "~/components/Background";
import LinkButton from "~/components/LinkButton";
import { LinkType } from "~/store/linksStore";
import { api } from "~/utils/api";
export default function Linkbud() {
  const router = useRouter();
  const { data: userData } = api.links.getLinksByEndpoint.useQuery({
    endpoint: router.query.endpoint as string,
  });
  const [profilePicture, setProfilePicture] = useState("");
  useEffect(() => {
    if (userData?.user.image) {
      setProfilePicture(userData.user.image);
    }
  }, [userData?.user.image]);

  return (
    <>
      <Head>
        <title>Linkbud</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <main className="min-h-screen w-full">
        <div className="flex flex-col items-center justify-start gap-2 px-8 py-20 text-white sm:mx-auto sm:w-96">
          <Background theme="black" image={profilePicture} />
          <img
            className="h-20 rounded-full"
            src={profilePicture}
            alt="profile picture"
            referrerPolicy="no-referrer"
          />
          <h1 className="text-xl font-semibold">Hansen Limanta</h1>
          <h2 className="text-center">
            Description Lorem ipsum dolor sit, amet consectetur adipisicing
            elit. Eveniet, quas?
          </h2>
          <div className="my-4 flex w-full flex-col gap-4">
            {userData?.links ? (
              userData.links.map((dbLink) => {
                if (dbLink.type === LinkType.Classic) {
                  return (
                    <LinkButton key={dbLink.id} theme="white" link={dbLink} />
                  );
                } else if (dbLink.type === LinkType.Header) {
                  return (
                    <div key={dbLink.id} className="w-full text-center">
                      <h1 className="text-1xl font-semibold">{dbLink.title}</h1>
                    </div>
                  );
                }
              })
            ) : (
              <></>
            )}
          </div>
        </div>
      </main>
    </>
  );
}
