import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
// import { signIn, signOut, useSession } from "next-auth/react";
// import Link from "next/link";
// import { api } from "~/utils/api";

export default function Home() {
  // const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Linkbud</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen w-full bg-stone-100">
        <nav className="fixed top-0 z-20 m-auto w-full">
          <div className="mx-36 mt-12 flex max-w-[1728px] items-center justify-between rounded-full bg-white px-8 py-4">
            <div className="flex items-center justify-start gap-6">
              <p className="cursor-pointer px-4 text-3xl font-bold">Linkbud</p>
              <p>Templates</p>
              <p>Marketplace</p>
              <p>Discover</p>
              <p>Pricing</p>
              <p>Learn</p>
            </div>
            <div>
              <Link href="/admin">
                <button className="rounded-full bg-pink-300 px-8 py-4 font-medium transition hover:bg-pink-400">
                  Login
                </button>
              </Link>
            </div>
          </div>
        </nav>
        <div className="flex h-screen w-full bg-lime-600 px-36">
          <div className="flex flex-1 flex-col items-start justify-center gap-6">
            <h1 className="text-7xl font-extrabold">
              Everything you are. In one, simple link in bio.
            </h1>
            <h2 className="text-lg font-medium">
              Join 40M+ people using Linktree for their link in bio. One link to
              help you share everything you create, curate and sell from your
              Instagram, TikTok, Twitter, YouTube and other social media
              profiles.
            </h2>
            <div className="flex gap-3">
              <input
                className="rounded-md p-4"
                type="text"
                placeholder="link.bud/yourname"
              />
              <button className="rounded-full bg-pink-300 px-8 py-4 font-medium transition hover:bg-pink-400">
                Claim your Linkbud
              </button>
            </div>
          </div>
          <div className="flex flex-1 items-center justify-center">
            <div className="relative h-[600px] w-[350px] rounded-lg">
              <Image
                alt="example"
                src="/linkbud-example.png"
                objectFit="cover"
                fill
              />
            </div>
          </div>
        </div>
      </main>
      {/* <main className=" flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> App
          </h1>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/usage/first-steps"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">First Steps →</h3>
              <div className="text-lg">
                Just the basics - Everything you need to know to set up your
                database and authentication.
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
              href="https://create.t3.gg/en/introduction"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Documentation →</h3>
              <div className="text-lg">
                Learn more about Create T3 App, the libraries it uses, and how
                to deploy it.
              </div>
            </Link>
          </div>
          <div className="flex flex-col items-center gap-2">
            <p className="text-2xl text-white">
              {hello.data ? hello.data.greeting : "Loading tRPC query..."}
            </p>
            <Link
              href="/linkbud"
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-white/10 p-4 text-white hover:bg-white/20"
            >
              <div>Go to Linkbud</div>
            </Link>
            <AuthShowcase />
          </div>
        </div>
      </main> */}
    </>
  );
}

// function AuthShowcase() {
//   const { data: sessionData } = useSession();

//   const { data: secretMessage } = api.example.getSecretMessage.useQuery(
//     undefined, // no input
//     { enabled: sessionData?.user !== undefined },
//   );

//   return (
//     <div className="flex flex-col items-center justify-center gap-4">
//       <p className="text-center text-2xl text-white">
//         {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
//         {secretMessage && <span> - {secretMessage}</span>}
//       </p>
//       <button
//         className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
//         onClick={sessionData ? () => void signOut() : () => void signIn()}
//       >
//         {sessionData ? "Sign out" : "Sign in"}
//       </button>
//     </div>
//   );
// }
